// Generated by my-summer-game tools/export_prop_library.sh from the Blender prop
// library (assets/prop_library/props.blend). Edit the library and re-export; do not edit by hand.

/** A static prop from the Blender library, exported to public/props/library. */
export type LibraryProp = {
  /** The .glb: origin at the centre of its foot, front facing +Z, in metres. */
  model: string;
  name: string;
  /** The Blender asset catalog it is filed under, e.g. 'Containers/Crates'. */
  catalog: string;
  /** Width (X), height and depth (Z) in metres. */
  size: readonly [number, number, number];
  /** Whether investigators bump into it. Small clutter is walked through. */
  solid: boolean;
  credit: string;
  /** A 128 px thumbnail, for the set-dressing tray. */
  preview: string;
};

export const PROP_LIBRARY = {
  'barrel': {
    model: '/props/library/barrel.glb',
    name: "Wooden Barrel",
    catalog: 'Containers/Barrels',
    size: [0.742, 0.871, 0.756],
    solid: true,
    credit: "\"Wooden Barrel\" by James Ray Cock — https://polyhaven.com/a/wine_barrel_01 (CC0)",
    preview: '/props/library/previews/barrel.webp',
  },
  'candlestick': {
    model: '/props/library/candlestick.glb',
    name: "Wooden Candlestick",
    catalog: 'Lighting',
    size: [0.097, 0.22, 0.099],
    solid: false,
    credit: "\"Wooden Candlestick\" by Josh Dean — https://polyhaven.com/a/wooden_candlestick (CC0)",
    preview: '/props/library/previews/candlestick.webp',
  },
  'iron-safe': {
    model: '/props/library/iron-safe.glb',
    name: "Antique Iron Safe",
    catalog: 'Containers/Safes',
    size: [0.622, 0.984, 0.82],
    solid: true,
    credit: "\"Antique Iron Safe\" by pixelgrapher — https://sketchfab.com/3d-models/antique-iron-safe-196cf0d3d5094b50874dbf51064a7d3e (CC BY 4.0)",
    preview: '/props/library/previews/iron-safe.webp',
  },
  'long-bench': {
    model: '/props/library/long-bench.glb',
    name: "Long Wooden Bench",
    catalog: 'Furniture/Seating',
    size: [1.8, 0.549, 0.657],
    solid: true,
    credit: "\"Long Wooden Bench\" by Ethan Place — https://polyhaven.com/a/WoodenTable_01 (CC0)",
    preview: '/props/library/previews/long-bench.webp',
  },
  'painted-cabinet': {
    model: '/props/library/painted-cabinet.glb',
    name: "Painted Wooden Cabinet",
    catalog: 'Furniture/Storage',
    size: [1.195, 1.182, 0.617],
    solid: true,
    credit: "\"Painted Wooden Cabinet\" by Kirill Sannikov — https://polyhaven.com/a/painted_wooden_cabinet (CC0)",
    preview: '/props/library/previews/painted-cabinet.webp',
  },
  'rocking-chair': {
    model: '/props/library/rocking-chair.glb',
    name: "Rocking Chair",
    catalog: 'Furniture/Seating',
    size: [0.708, 0.995, 0.833],
    solid: true,
    credit: "\"Rocking Chair\" by Jorge Camacho — https://polyhaven.com/a/Rockingchair_01 (CC0)",
    preview: '/props/library/previews/rocking-chair.webp',
  },
  'sea-chest': {
    model: '/props/library/sea-chest.glb',
    name: "Sea Chest",
    catalog: 'Containers',
    size: [0.959, 0.619, 0.523],
    solid: true,
    credit: "\"Sea Chest\" by Rico Cilliers — https://polyhaven.com/a/treasure_chest (CC0)",
    preview: '/props/library/previews/sea-chest.webp',
  },
  'wooden-bucket': {
    model: '/props/library/wooden-bucket.glb',
    name: "Wooden Bucket",
    catalog: 'Containers',
    size: [0.367, 0.55, 0.342],
    solid: false,
    credit: "\"Wooden Bucket\" by James Ray Cock — https://polyhaven.com/a/wooden_bucket_01 (CC0)",
    preview: '/props/library/previews/wooden-bucket.webp',
  },
  'wooden-crate': {
    model: '/props/library/wooden-crate.glb',
    name: "Wooden Crate",
    catalog: 'Containers/Crates',
    size: [0.825, 0.35, 0.409],
    solid: true,
    credit: "\"Wooden Crate\" by James Ray Cock — https://polyhaven.com/a/wooden_crate_01 (CC0)",
    preview: '/props/library/previews/wooden-crate.webp',
  },
  'wooden-crate-large': {
    model: '/props/library/wooden-crate-large.glb',
    name: "Large Wooden Crate",
    catalog: 'Containers/Crates',
    size: [1.166, 0.464, 0.529],
    solid: true,
    credit: "\"Large Wooden Crate\" by James Ray Cock, Jurita Burger — https://polyhaven.com/a/wooden_crate_02 (CC0)",
    preview: '/props/library/previews/wooden-crate-large.webp',
  },
  'wooden-lantern': {
    model: '/props/library/wooden-lantern.glb',
    name: "Wooden Lantern",
    catalog: 'Lighting',
    size: [0.221, 0.53, 0.235],
    solid: false,
    credit: "\"Wooden Lantern\" by James Ray Cock — https://polyhaven.com/a/wooden_lantern_01 (CC0)",
    preview: '/props/library/previews/wooden-lantern.webp',
  },
  'wooden-stool': {
    model: '/props/library/wooden-stool.glb',
    name: "Wooden Stool",
    catalog: 'Furniture/Seating',
    size: [0.663, 0.455, 0.458],
    solid: true,
    credit: "\"Wooden Stool\" by Kuutti Siitonen — https://polyhaven.com/a/wooden_stool_02 (CC0)",
    preview: '/props/library/previews/wooden-stool.webp',
  },
  'worn-bookshelf': {
    model: '/props/library/worn-bookshelf.glb',
    name: "Worn Bookshelf",
    catalog: 'Furniture/Storage',
    size: [1.374, 2.063, 0.581],
    solid: true,
    credit: "\"Worn Bookshelf\" by Ulan Cabanilla — https://polyhaven.com/a/wooden_bookshelf_worn (CC0)",
    preview: '/props/library/previews/worn-bookshelf.webp',
  },
} as const satisfies Record<string, LibraryProp>;

export type PropAssetId = keyof typeof PROP_LIBRARY;
